import type { Metadata } from "next";
import { Exo, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Toaster } from "sonner";
import SessionProviderServer from "@/components/SessionProviderServer/SessionProviderServer";
import TanstackProvider from "@/providers/TanstackProvider/Tanstack.Provider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  fallback: ["Exo Fallback", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${exo.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col ">
        <SessionProviderServer>
          <TanstackProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
          <Toaster richColors position="top-left" />
          </TanstackProvider>
        </SessionProviderServer>
      </body>
    </html>
  );
}
